#!/usr/bin/env python3
"""Regenerate the root-level /hermes-skills/ aggregator for Hermes Agent.

Hermes' `hermes skills tap add <owner>/<repo>` (and `hermes skills
browse`/`search`) only looks one directory level below a single `skills/`
path in the repo by default — see `_list_skills_in_repo` /
`GitHubSource.DEFAULT_TAPS` in hermes-agent's `tools/skills_hub.py`. This repo
is ALSO a Claude Code plugin marketplace, and the repo-root `skills/`
directory is already claimed by the `synology-nas` plugin's own
`.claude-plugin/plugin.json` (`"skills": "./skills/"`) — Claude Code walks
every subdirectory under a plugin's configured skills path as one of *that
plugin's* skills, so dropping the other plugins' skills in there too would
make Claude falsely advertise them all as part of synology-nas. Hence a
separate `hermes-skills/` directory instead of reusing `skills/`.

This script mirrors every plugin's skill directory (source of truth stays
under `<plugin>/skills/<name>/`, required by that plugin's own
`.claude-plugin/plugin.json`) into a flat top-level `hermes-skills/<name>/`.
Point a Hermes tap at this path (see README's Hermes Agent section — the tap
CLI only offers the `skills/` default, so add/edit the entry in
`~/.hermes/taps.json` with `"path": "hermes-skills/"`) to get the whole
catalog in one shot; re-run this script after editing any plugin's SKILL.md
(or its references/scripts) to refresh the copies.

Usage: python3 scripts/sync_hermes_skills.py [--check]
  --check   exit 1 if the aggregator is stale instead of rewriting it (CI use)
"""
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
AGGREGATE_DIR = ROOT / "hermes-skills"
MARKER = ".synced-from"

# (plugin skill dir relative to ROOT) -> synced under hermes-skills/<same dir name>/
SOURCES = [
    "skills/synology-control",
    "sonarr-control/skills/sonarr-control",
    "radarr-control/skills/radarr-control",
    "sabnzbd-control/skills/sabnzbd-control",
    "tdarr-control/skills/tdarr-control",
    "gitlab/skills/gitlab-control",
    "emby/skills/emby-control",
    "romm/skills/romm-control",
    "unifi/skills/unifi-control",
    "comfyui-control/skills/comfyui-control",
    "opencode-control/skills/opencode-control",
    "searxng-control/skills/searxng-control",
    "deep-integration-builder/skills/building-deep-integrations",
]


def main() -> int:
    check_only = "--check" in sys.argv
    stale = []
    synced = 0

    for rel in SOURCES:
        src = ROOT / rel
        name = src.name
        dest = AGGREGATE_DIR / name

        if not src.is_dir():
            print(f"SKIP (missing source): {rel}")
            continue

        if dest.exists() and not (dest / MARKER).exists():
            print(f"REFUSING to overwrite {dest} — no {MARKER} marker "
                  f"(looks hand-authored, not generated by this script)")
            continue

        if check_only:
            if not dest.exists():
                stale.append(name)
            continue

        if dest.exists():
            shutil.rmtree(dest)
        shutil.copytree(src, dest)
        (dest / MARKER).write_text(
            f"Generated by scripts/sync_hermes_skills.py from {rel}\n"
            f"Do not edit here — edit the source and re-run the script.\n",
            encoding="utf-8",
        )
        synced += 1
        print(f"synced: {rel} -> {AGGREGATE_DIR.name}/{name}/")

    if check_only:
        if stale:
            print(f"STALE: {len(stale)} skill(s) missing from aggregator: {stale}")
            return 1
        print("Aggregator up to date.")
        return 0

    print(f"\n{synced} skill(s) synced into {AGGREGATE_DIR}/")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
